# Generated by Django 4.2.1 on 2023-05-12 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Числовое значение')),
                ('progress', models.CharField(max_length=35, verbose_name='Прогресс')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Достижение(не более 4)',
                'verbose_name_plural': 'Достижения(не более 4)',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование навыка')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Усвоение навыка(%)')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='UserSelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('surname', models.CharField(max_length=155, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('dsc', models.TextField(verbose_name='Описание о себе')),
                ('photo_desktop', models.ImageField(upload_to='photo/desktop/%Y/%m/%d/', verbose_name='Фотография(610х1020)')),
                ('photo_mobile', models.ImageField(upload_to='photo/mobile/%Y/%m/%d/', verbose_name='Фотография(300х300)')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('address', models.CharField(max_length=155, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=155, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('vacancy', models.CharField(max_length=255, verbose_name='Вакансия')),
                ('resume', models.FileField(upload_to='photo/resume/%Y/%m/%d/', verbose_name='Резюме(pdf)')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
