# Generated by Django 4.2.1 on 2023-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0003_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Дорожная карта', 'verbose_name_plural': 'Дорожные карты'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='dsc',
            field=models.CharField(max_length=255, verbose_name='Описание(300 символов)'),
        ),
    ]
