# Generated by Django 4.2.1 on 2023-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0004_alter_experience_options_alter_experience_dsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='dsc',
            field=models.CharField(max_length=300, verbose_name='Описание(300 символов)'),
        ),
    ]
