# Generated by Django 4.2.1 on 2023-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0005_alter_experience_dsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
