# Generated by Django 4.2.1 on 2023-05-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0008_contact_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
