# Generated by Django 4.2.1 on 2023-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('mail', models.CharField(max_length=155, verbose_name='Почта')),
                ('company', models.CharField(max_length=155, verbose_name='Компания')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='userself',
            name='salary',
            field=models.IntegerField(default=30000, verbose_name='Желаемая зарплата'),
            preserve_default=False,
        ),
    ]
