# Generated by Django 4.1.4 on 2023-05-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0012_feedback_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=' Название')),
            ],
            options={
                'verbose_name': 'Роль в проекте',
                'verbose_name_plural': 'Роли в проекте',
            },
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы в проектах',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('photo', models.ImageField(upload_to='photo/project/%Y/%m/%d/', verbose_name='Фотография')),
                ('stack', models.CharField(max_length=155, verbose_name='Стек технологий')),
                ('preview', models.CharField(max_length=255, verbose_name='Ссылка на проект')),
                ('time', models.DateTimeField(verbose_name='Дата выполнения')),
                ('dsc', models.TextField(verbose_name='Описание проекта')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunis.role', verbose_name='Роль')),
                ('type_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tunis.typeproject', verbose_name='Тип проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
