# Generated by Django 4.1.4 on 2023-05-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunis', '0013_role_typeproject_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
